Ores:
  Diamond:
    #What the item-name will be in-game. You cannot include color codes here.
    Name: "Flawless Diamond"
    #What color/formatting should the itemname have?
    #For color codes to work you *MUST* use '§' not '&'
    #Guide for colorcodes: https://www.addictivetips.com/app/uploads/2019/08/Minecraft-Color-Codes-and-Format-Codes.jpg
    Formatting: "§b"
    #The material for the item
    Material_Item: "DIAMOND"
    #Only add regular version of the ore, deepslate is automatically accounted for.
    Material_Block: "DIAMOND_ORE"
    #The drop-chance in percent
    Chance: 50
    #The text that will be displayed in the item-lore
    Description: "A rare form of Diamond!"
    #Does the block have a deepslate version? True for yes, False for no
    Deepslate: true
  Emerald:
    Name: "Flawless Emerald"
    Formatting: "§2"
    Material_Item: "EMERALD"
    Material_Block: "EMERALD_ORE"
    Chance: 50
    Description: "A rare form of Emerald!"
    Deepslate: true
  Gold:
    Name: "Pure Gold"
    Formatting: "§e"
    Material_Item: "GOLD_INGOT"
    Material_Block: "GOLD_ORE"
    Chance: 50
    Description: "A rare form of Gold!"
    Deepslate: true
  Iron:
    Name: "Pure Iron"
    Formatting: "§f"
    Material_Item: "IRON_INGOT"
    Material_Block: "IRON_ORE"
    Chance: 50
    Description: "A rare form of Iron!"
    Deepslate: true
  Redstone:
    Name: "Pure Redstone"
    Formatting: "§c"
    Material_Item: "REDSTONE"
    Material_Block: "REDSTONE_ORE"
    Chance: 50
    Description: "A rare form of Redstone!"
    Deepslate: true
  Copper:
    Name: "Pure Copper"
    Formatting: "§6"
    Material_Item: "COPPER_INGOT"
    Material_Block: "COPPER_ORE"
    Chance: 50
    Description: "A rare form of copper!"
    Deepslate: true
  Coal:
    Name: "Pure Coal"
    Formatting: "§8"
    Material_Item: "COAL"
    Material_Block: "COAL_ORE"
    Chance: 50
    Description: "A rare form of coal!"
    Deepslate: true
  Lapis:
    Name: "Flawless Lapis"
    Formatting: "§9"
    Material_Item: "LAPIS_LAZULI"
    Material_Block: "LAPIS_ORE"
    Chance: 50
    Description: "A rare form of Lapis"
    Deepslate: true
  Amethyst:
    Name: "Flawless Amethyst Shard"
    Formatting: "§d"
    Material_Item: "AMETHYST_SHARD"
    Material_Block: "AMETHYST_CLUSTER"
    Chance: 50
    Description: "A rare form of Amethyst"
    Deepslate: false
#This is the global setting for dropchance, if there is no Chance specified in the item it will use this value
Globals:
  DropChance:
    Use: false
    Chance: 50
  #Add trigger in config to switch between global setting and individual setting for easier testing
  #if (string starts with x, split start of string take first index of split string.contains y, if false continue, else replace